export const CHARACTERS_FETCH_REQUESTED = 'CHARACTERS_FETCH_REQUESTED';
export const CHARACTERS_FETCH_SUCCEEDED = 'CHARACTERS_FETCH_SUCCEEDED';
export const CHARACTERS_FETCH_FAILED = 'CHARACTERS_FETCH_FAILED';
export const REMOVE_CURRENT_CHARACTER = 'REMOVE_CURRENT_CHARACTER';
